### ISSUE TITLE
Horizon - Generated Static Content 404

### ISSUE THREAD

**Issue by byronmccollum** [rcbops/ansible-lxc-rpc#108]
Occasionally, generated static content will not get generated, causing a 404.
### Browser Console Log

```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (https://23.253.159.223/static/dashboard/js/f81063bc9af9.js)
```
### Apache Error Log - Infra2

```
[Thu Sep 11 17:32:29.071060 2014] [core:info] [pid 3990:tid 140239825704704] [client 172.29.236.1:51523] AH00128: File does not exist: /opt/horizon/lib/python2.7/site-packages/openstack_dashboard/static/dashboard/js/f81063bc9af9.js, referer: https://23.253.159.223/project/volumes/?tab=volumes_and_snapshots__snapshots_tab
```
### Horizon Static Content - Infra2

```
root@infra2_horizon_container-dfb90b58:/opt/horizon/lib/python2.7/site-packages/openstack_dashboard/static/dashboard# ls -l
total 12
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 fonts
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 img
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 less
```
### Horizon Static Content - Infra1

```
root@infra1_horizon_container-bf1987eb:/opt/horizon/lib/python2.7/site-packages/openstack_dashboard/static/dashboard# ls -l
total 20
drwxr-xr-x 2 www-data www-data 4096 Sep 10 18:26 css
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:42 fonts
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:42 img
drwxr-xr-x 2 www-data www-data 4096 Sep 10 18:26 js
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:42 less
```
### Horizon Static Content - Infra3

```
root@infra3_horizon_container-f726fc25:/opt/horizon/lib/python2.7/site-packages/openstack_dashboard/static/dashboard# ls -l
total 20
drwxr-xr-x 2 www-data www-data 4096 Sep 11 08:40 css
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 fonts
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 img
drwxr-xr-x 2 www-data www-data 4096 Sep 11 08:41 js
drwxr-xr-x 2 www-data www-data 4096 Sep 10 16:41 less
```

**Comment by cloudnull** [comment]
this should be resolved in https://github.com/rcbops/ansible-lxc-rpc/pull/94 the horizon play was reworked for key distribution and the out of band processes were removed.

**Comment by byronmccollum** [comment]
@cloudnull This is still happening in a 3 infra node config.

**Comment by cloudnull** [comment]
While this is throwing an error, do you see issues with horizon?

**Comment by byronmccollum** [comment]
Yes, unstyled pages, and missing JavaScript functionality.
